Repository MDeLuise/plant-it, pull requests merged in 2023-09, with the labels that each got.

#2 Fix-docker-compose
  deployment/docker-compose.yml
Labels: bug

#3 improve manifest
  frontend/public/manifest.json
Labels: documentation

#5 Fix mvn wrappers not working
  backend/.mvn/wrapper/maven-wrapper.jar
  backend/.mvn/wrapper/maven-wrapper.properties
  backend/mvnw
  backend/mvnw.cmd
  backend/pom.xml
Labels: bug

#6 Add contribue section in the main `README`
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/fr.yml
  README.md
Labels: documentation

#7 Add project license
  LICENSE.txt
  README.md
Labels: documentation

#11 Add configurable CORS origin through environment variable
  README.md
  backend/pom.xml
  backend/src/main/java/com/github/mdeluise/plantit/ApplicationConfig.java
  backend/src/main/java/com/github/mdeluise/plantit/security/ApplicationSecurityConfig.java
  backend/src/main/resources/application-dev.properties
  backend/src/main/resources/application-integration.properties
  backend/src/main/resources/application.properties
  deployment/backend.env
  deployment/frontend.env
Labels: enhancement

#21 Simplify deployment - remove `nginx` service
  README.md
  backend/src/main/java/com/github/mdeluise/plantit/security/ApplicationSecurityConfig.java
  backend/src/main/resources/application-dev.properties
  backend/src/main/resources/application-integration.properties
  backend/src/main/resources/application.properties
  deployment/backend.env
  deployment/default.conf
  deployment/docker-compose.yml
  deployment/frontend.env
  frontend/.env
  frontend/src/App.tsx
  frontend/src/common.ts
  frontend/src/components/Auth.tsx
Labels: enhancement
